name: Markdown lint

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  markdown:
    name: markdown lint
    uses: nosborn/github-action-markdown-cli@v3.0.1
    with:
        files: .