name: lint

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  super-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Lint
        uses: github/super-linter/slim@v4
        env:
          LINTER_RULES_PATH: '.'
          MARKDOWN_CONFIG_FILE: .markdownlint.json
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_MARKDOWN: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}