name: Check

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  yaml:
    name: Lining Yaml files
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Linting Yaml files
        run: |
          yarn run lint:yml:setup
          yarn run lint:yml

  markdown:
    name: Lining Markdown files
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Linting MD files
        run: |
          yarn run lint:md:setup
          yarn run lint:md
